package Modelo;
// Generated 16-nov-2017 23:15:29 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Accesorio generated by hbm2java
 */
public class Accesorio  implements java.io.Serializable {


     private Integer idAccesorio;
     private String nombre;
     private int precio;
     private Integer stock;
     private Set productos = new HashSet();

    public Accesorio() {
    }

	
    public Accesorio(String nombre, int precio) {
        this.nombre = nombre;
        this.precio = precio;
    }
    public Accesorio(String nombre, int precio, Integer stock, Set productos) {
       this.nombre = nombre;
       this.precio = precio;
       this.stock = stock;
       this.productos = productos;
    }
   
    public Integer getIdAccesorio() {
        return this.idAccesorio;
    }
    
    public void setIdAccesorio(Integer idAccesorio) {
        this.idAccesorio = idAccesorio;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(int precio) {
        this.precio = precio;
    }
    public Integer getStock() {
        return this.stock;
    }
    
    public void setStock(Integer stock) {
        this.stock = stock;
    }
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }




}


