package Modelo;
// Generated 16-nov-2017 23:15:29 by Hibernate Tools 4.3.1



/**
 * Documento generated by hbm2java
 */
public class Documento  implements java.io.Serializable {


     private Integer idDocumento;
     private Pedido pedido;
     private TipoDocumento tipoDocumento;

    public Documento() {
    }

    public Documento(Pedido pedido, TipoDocumento tipoDocumento) {
       this.pedido = pedido;
       this.tipoDocumento = tipoDocumento;
    }
   
    public Integer getIdDocumento() {
        return this.idDocumento;
    }
    
    public void setIdDocumento(Integer idDocumento) {
        this.idDocumento = idDocumento;
    }
    public Pedido getPedido() {
        return this.pedido;
    }
    
    public void setPedido(Pedido pedido) {
        this.pedido = pedido;
    }
    public TipoDocumento getTipoDocumento() {
        return this.tipoDocumento;
    }
    
    public void setTipoDocumento(TipoDocumento tipoDocumento) {
        this.tipoDocumento = tipoDocumento;
    }




}


